[project]
name = "image-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sumygin", email = "mikhailsumygin@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
image-tools = "image_tools:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
